/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'starhai' at '1/22/17 11:27 AM' with Gradle 2.14.1
 *
 * @author starhai, @date 1/22/17 11:27 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
